version: '3.8'

services:
    books:
        build: 
            context: .
            dockerfile: ./docker/books-dev.dockerfile
        container_name: books_container_test_microservices
        image: r4deu51/books_test_microservices
        networks:
            - network
        restart: always
        volumes:
            - ./services/books:/app:rw

    authors:
        build: 
            context: .
            dockerfile: ./docker/authors-dev.dockerfile
        container_name: authors_container_test_microservices
        image: r4deu51/authors_test_microservices
        networks:
            - network
        restart: always
        volumes:
            - ./services/authors:/app:rw

    rabbitmq:
        build: 
            context: .
            dockerfile: ./docker/rabbitmq.dockerfile
        container_name: rabbitmq_container_test_microservices
        image: r4deu51/rabbitmq_test_microservices
        networks:
            - network
        restart: always

    nginx:
        build: 
            context: .
            dockerfile: ./docker/nginx.dockerfile
        container_name: nginx_container_test_microservices
        image: r4deu51/nginx_test_microservices
        networks:
            - network
        restart: always
        ports:
          - "80:80"

    mongodb:
        build: 
            context: .
            dockerfile: ./docker/mongodb.dockerfile
        container_name: mongodb_container_test_microservices
        image: r4deu51/mongodb_test_microservices
        networks:
            - network
        restart: always

networks:
    network:
        driver: bridge